org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
package_name=org.supertuxkart.stk_dbg
compile_sdk_version=35
min_sdk_version=21
target_sdk_version=35
ndk_version=28.2.13676358
compile_arch=arm64-v8a
cpu_core=-j33
version_name=git
version_code=1
keystore=empty
storepass=empty
alias=empty
